name: CI Pipeline
run-name: ${{github.actor}} is learning GitHub Actions
on: [push]
jobs:
  behave-testing:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      # This checks out the code from the repository so that the workflow can work on it.
      - name: list repo
        run:
          ls

      - name: Set up Python environment
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'  # Specify Python version (or any other version you need)

      - name: Install Behave
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install --upgrade pip  # Upgrade pip to the latest version
          pip install behave  # Install Behave


      - name: Run Behave tests
        run: |
          source venv/bin/activate  # Activate the virtual environment
          behave --format plain --outfile ./test-results/results.txt  # Save results as text

      # Upload the test results as an artifact
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/results.txt


      - name: Check test results for issues and create an issue if any test fails
        run: |
          # Check if "failed" is found in the results.txt (you can adjust this search based on your test output)
          if grep -q "failed" ./test-results/results.txt; then
            echo "Tests failed. Creating GitHub issue..."
            
            # Use GitHub's REST API to create a new issue in the repository
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"title": "Test Failures Detected in CI Pipeline", "body": "The Behave tests encountered failures. Please review the results in the artifacts for more details."}' \
              https://api.github.com/repos/${{ github.repository }}/issues
          else
            echo "All tests passed successfully. No issues will be created."
          fi
